# Generated by Django 3.2.4 on 2021-08-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproject', '0004_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=40)),
                ('emailid', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=80)),
                ('phoneno', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
