# Generated by Django 3.2.4 on 2021-08-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eproject', '0005_auto_20210801_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mycustomer',
        ),
    ]
